### ISSUE TITLE
I cant see the mqtt2graphice source on the graphite webapp

### ISSUE THREAD

**Issue by eliabieri** [jpmens/mqtt2graphite#4]
I started the mqtt2graphite.py script and configured everything before accordingly.
however, I cant see the source on the webapp?
do you have an idea why?
If I manually inject data, I can see it immediately in the web app:

while true
do
  echo -n "example.statsd.counter.changed:$(((RANDOM % 10) + 1))|c" | nc -w 1 -u localhost 8125
done

**Comment by isigmund** [comment]
I have the same issue, I believe it has to do with the fact that carbon by default listens on port 2003 using the TCP protocol. The implementation here sends data via UDP though. See https://answers.launchpad.net/graphite/+question/216002 on how you could configure carbon to liten on UDP.
I will probably go a different road. I have forked this repo and try to make it work on TCP and UDP making it configurable which protocol to use. Another option is to switch to PICKLE which should be more suitable to send JSON formatted data, since you can send a whole JSON in one batch instad of chunking it up in separate lines

take care
   Ingo
